"""remove user_id from feedback

Revision ID: 021b13c45534
Revises: 619457265113
Create Date: 2024-12-04 03:40:35.767994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "021b13c45534"
down_revision: Union[str, None] = "619457265113"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("feedbacks_user_id_fkey", "feedbacks", type_="foreignkey")
    op.drop_column("feedbacks", "user_id")
    # op.create_unique_constraint('unique_request_comment_vote', 'request_comment_votes', ['user_id', 'comment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_request_comment_vote", "request_comment_votes", type_="unique")
    op.add_column(
        "feedbacks", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key("feedbacks_user_id_fkey", "feedbacks", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###
