"""Added VideoCreate model or updated Video model

Revision ID: 074b9a1bf5cd
Revises: 0ae22da256fb
Create Date: 2024-10-14 14:09:48.842725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '074b9a1bf5cd'
down_revision: Union[str, None] = '0ae22da256fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notes', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_notes_title', table_name='notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_notes_title', 'notes', ['title'], unique=False)
    op.alter_column('notes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('notes', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notes', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
