"""add_showcase_urls_and_file_fields

Revision ID: 0cd8bdecc7b6
Revises: 26c9ba475a09
Create Date: 2025-01-05 20:37:39.800715

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0cd8bdecc7b6"
down_revision: Union[str, None] = "26c9ba475a09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "showcase_videos",
        sa.Column("showcase_id", sa.Integer(), nullable=True),
        sa.Column("video_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["showcase_id"], ["showcases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("showcase_id", "video_id", name="unique_showcase_video"),
    )
    # op.create_unique_constraint('unique_request_comment_vote', 'request_comment_votes', ['user_id', 'comment_id'])
    op.add_column("showcases", sa.Column("image_url", sa.String(), nullable=True))
    op.add_column("showcases", sa.Column("readme_url", sa.String(), nullable=True))
    op.add_column("showcases", sa.Column("project_url", sa.String(), nullable=True))
    op.add_column("showcases", sa.Column("repository_url", sa.String(), nullable=True))
    op.add_column("showcases", sa.Column("demo_url", sa.String(), nullable=True))
    op.add_column(
        "showcases", sa.Column("developer_profile_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "showcases", "developer_profiles", ["developer_profile_id"], ["id"]
    )
    op.drop_column("showcases", "readme")
    op.drop_column("showcases", "video_ids")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "showcases",
        sa.Column(
            "video_ids",
            postgresql.ARRAY(sa.INTEGER()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "showcases", sa.Column("readme", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "showcases", type_="foreignkey")
    op.drop_column("showcases", "developer_profile_id")
    op.drop_column("showcases", "demo_url")
    op.drop_column("showcases", "repository_url")
    op.drop_column("showcases", "project_url")
    op.drop_column("showcases", "readme_url")
    op.drop_column("showcases", "image_url")
    # op.drop_constraint('unique_request_comment_vote', 'request_comment_votes', type_='unique')
    op.drop_table("showcase_videos")
    # ### end Alembic commands ###
