"""Update role column in User model

Revision ID: 1f395ee358f1
Revises: f18487be8795
Create Date: 2025-03-10 13:28:22.037815

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f395ee358f1"
down_revision: Union[str, None] = "f18487be8795"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('unique_request_comment_vote', 'request_comment_votes', ['user_id', 'comment_id'])
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_request_comment_vote', 'request_comment_votes', type_='unique')
    # ### end Alembic commands ###
    pass
