"""trying to get project showcase to work

Revision ID: 26c9ba475a09
Revises: f59e2df0b9e7
Create Date: 2025-01-05 20:01:19.574042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26c9ba475a09"
down_revision: Union[str, None] = "f59e2df0b9e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('unique_request_comment_vote', 'request_comment_votes', ['user_id', 'comment_id'])
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_request_comment_vote', 'request_comment_votes', type_='unique')
    # ### end Alembic commands ###
    pass
