"""Add external_source to ConversationMessage

Revision ID: 33b0eb52f56d
Revises: 67f2d8127620
Create Date: 2025-04-05 17:42:42.841774

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "33b0eb52f56d"
down_revision: Union[str, None] = "67f2d8127620"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation_messages",
        sa.Column("external_source", sa.String(), nullable=True),
    )
    # op.create_unique_constraint('unique_request_comment_vote', 'request_comment_votes', ['user_id', 'comment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_request_comment_vote', 'request_comment_votes', type_='unique')
    op.drop_column("conversation_messages", "external_source")
    # ### end Alembic commands ###
