"""Create newsletter table

Revision ID: 3b80f63162bf
Revises: a25d9af5def8
Create Date: 2024-10-10 08:19:01.550502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b80f63162bf'
down_revision: Union[str, None] = 'a25d9af5def8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_email'), 'newsletter', ['email'], unique=True)
    op.create_index(op.f('ix_newsletter_id'), 'newsletter', ['id'], unique=False)
    op.create_unique_constraint('unique_vote', 'votes', ['user_id', 'post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_vote', 'votes', type_='unique')
    op.drop_index(op.f('ix_newsletter_id'), table_name='newsletter')
    op.drop_index(op.f('ix_newsletter_email'), table_name='newsletter')
    op.drop_table('newsletter')
    # ### end Alembic commands ###
