"""add_idea_collaboration_fields

Revision ID: 5bfa6f651145
Revises: cb318ddec2fc
Create Date: 2025-02-19 16:01:34.379054

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5bfa6f651145"
down_revision: Union[str, None] = "cb318ddec2fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('unique_request_comment_vote', 'request_comment_votes', ['user_id', 'comment_id'])
    op.add_column("requests", sa.Column("is_idea", sa.Boolean(), nullable=True))
    op.add_column(
        "requests", sa.Column("seeks_collaboration", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "requests", sa.Column("collaboration_details", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requests", "collaboration_details")
    op.drop_column("requests", "seeks_collaboration")
    op.drop_column("requests", "is_idea")
    # op.drop_constraint('unique_request_comment_vote', 'request_comment_votes', type_='unique')
    # ### end Alembic commands ###
