"""Add thumbnail_path to videos

Revision ID: 5f3d152aa8bc
Revises: 074b9a1bf5cd
Create Date: 2024-10-16 19:53:07.097079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f3d152aa8bc'
down_revision: Union[str, None] = '074b9a1bf5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('thumbnail_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'thumbnail_path')
    # ### end Alembic commands ###
