"""add name and email to feedback

Revision ID: 619457265113
Revises: 8eeb441e5389
Create Date: 2024-12-04 03:33:19.290456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "619457265113"
down_revision: Union[str, None] = "8eeb441e5389"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("feedbacks", sa.Column("name", sa.String(), nullable=True))
    op.add_column("feedbacks", sa.Column("email", sa.String(), nullable=True))
    # op.create_unique_constraint('unique_request_comment_vote', 'request_comment_votes', ['user_id', 'comment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_request_comment_vote", "request_comment_votes", type_="unique")
    op.drop_column("feedbacks", "email")
    op.drop_column("feedbacks", "name")
    # ### end Alembic commands ###
