"""add_showcase_rating_constraints

Revision ID: 64bd507d85a6
Revises: 0cd8bdecc7b6
Create Date: 2025-01-06 07:02:20.762097

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64bd507d85a6"
down_revision: Union[str, None] = "0cd8bdecc7b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(
    #     "unique_request_comment_vote",
    #     "request_comment_votes",
    #     ["user_id", "comment_id"],
    # )
    op.create_unique_constraint(
        "unique_showcase_rating", "showcase_ratings", ["showcase_id", "rater_id"]
    )
    op.create_check_constraint(
        "check_rating_range", "showcase_ratings", "rating >= 1 AND rating <= 5"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_rating_range", "showcase_ratings", type_="check")
    op.drop_constraint("unique_showcase_rating", "showcase_ratings", type_="unique")
    # op.drop_constraint(
    #     "unique_request_comment_vote", "request_comment_votes", type_="unique"
    # )
    # ### end Alembic commands ###
