"""Add project_id to notes

Revision ID: 6af986b1e2f2
Revises: 5f3d152aa8bc
Create Date: 2024-10-23 03:19:26.988090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af986b1e2f2'
down_revision: Union[str, None] = '5f3d152aa8bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'notes', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'project_id')
    # ### end Alembic commands ###
