"""add_showcase_and_ratings

Revision ID: 6fbecec6d92b
Revises: 1157cd107644
Create Date: 2025-01-06 21:16:15.676640

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6fbecec6d92b"
down_revision: Union[str, None] = "1157cd107644"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video_ratings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("rater_id", sa.Integer(), nullable=False),
        sa.Column("stars", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("stars >= 1 AND stars <= 5", name="check_video_stars_range"),
        sa.ForeignKeyConstraint(
            ["rater_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("video_id", "rater_id", name="unique_video_rating"),
    )
    op.create_index(op.f("ix_video_ratings_id"), "video_ratings", ["id"], unique=False)
    # op.create_unique_constraint('unique_request_comment_vote', 'request_comment_votes', ['user_id', 'comment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_request_comment_vote', 'request_comment_votes', type_='unique')
    op.drop_index(op.f("ix_video_ratings_id"), table_name="video_ratings")
    op.drop_table("video_ratings")
    # ### end Alembic commands ###
