"""modified rating model

Revision ID: 8a0d4a8bea58
Revises: 6933dbae44e0
Create Date: 2024-12-15 19:39:26.580773

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a0d4a8bea58"
down_revision: Union[str, None] = "6933dbae44e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("developer_ratings", sa.Column("user_id", sa.Integer(), nullable=False))
    op.drop_index("ix_developer_ratings_client_id", table_name="developer_ratings")
    op.drop_constraint("unique_developer_client_rating", "developer_ratings", type_="unique")
    op.create_index(
        op.f("ix_developer_ratings_user_id"), "developer_ratings", ["user_id"], unique=False
    )
    op.create_unique_constraint(
        "unique_developer_user_rating", "developer_ratings", ["developer_id", "user_id"]
    )
    op.drop_constraint("developer_ratings_client_id_fkey", "developer_ratings", type_="foreignkey")
    op.create_foreign_key(
        None, "developer_ratings", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("developer_ratings", "client_id")
    # op.create_unique_constraint('unique_request_comment_vote', 'request_comment_votes', ['user_id', 'comment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_request_comment_vote", "request_comment_votes", type_="unique")
    op.add_column(
        "developer_ratings",
        sa.Column("client_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "developer_ratings", type_="foreignkey")
    op.create_foreign_key(
        "developer_ratings_client_id_fkey",
        "developer_ratings",
        "client_profiles",
        ["client_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("unique_developer_user_rating", "developer_ratings", type_="unique")
    op.drop_index(op.f("ix_developer_ratings_user_id"), table_name="developer_ratings")
    op.create_unique_constraint(
        "unique_developer_client_rating", "developer_ratings", ["developer_id", "client_id"]
    )
    op.create_index(
        "ix_developer_ratings_client_id", "developer_ratings", ["client_id"], unique=False
    )
    op.drop_column("developer_ratings", "user_id")
    # ### end Alembic commands ###
