"""add_agreement_timestamps

Revision ID: a1d61220f4ca
Revises: 6f7d7419323b
Create Date: 2024-12-08 03:10:48.294911

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1d61220f4ca"
down_revision: Union[str, None] = "6f7d7419323b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agreements",
        sa.Column(
            "proposed_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "agreements", sa.Column("agreement_date", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    # op.create_unique_constraint('unique_request_comment_vote', 'request_comment_votes', ['user_id', 'comment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_request_comment_vote", "request_comment_votes", type_="unique")
    op.drop_column("agreements", "agreement_date")
    op.drop_column("agreements", "proposed_at")
    # ### end Alembic commands ###
