"""add command notes table

Revision ID: a6d260fcf2c3
Revises: c098bae8c0ba
Create Date: 2024-11-02 08:04:59.875349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d260fcf2c3'
down_revision: Union[str, None] = 'c098bae8c0ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('unique_vote', 'votes', ['user_id', 'post_id'])  # Comment this line
    pass  # Add this line since we can't have an empty function
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_vote', 'votes', type_='unique')  # Comment this line
    pass  # Add this line since we can't have an empty function
    # ### end Alembic commands ###