"""share token to Showcase

Revision ID: a97cc805219d
Revises: 6fbecec6d92b
Create Date: 2025-01-06 22:13:25.718999

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a97cc805219d"
down_revision: Union[str, None] = "6fbecec6d92b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('unique_request_comment_vote', 'request_comment_votes', ['user_id', 'comment_id'])
    op.add_column("showcases", sa.Column("share_token", sa.String(), nullable=True))
    op.create_unique_constraint(None, "showcases", ["share_token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "showcases", type_="unique")
    op.drop_column("showcases", "share_token")
    # op.drop_constraint('unique_request_comment_vote', 'request_comment_votes', type_='unique')
    # ### end Alembic commands ###
