"""remove_snagged_request_uniqueness

Revision ID: b0800814fb5b
Revises: cdc6cb944b2e
Create Date: 2024-12-26 16:18:04.857030

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b0800814fb5b"
down_revision: Union[str, None] = "cdc6cb944b2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "product_downloads_transaction_id_key", "product_downloads", type_="unique"
    )
    op.drop_column("product_downloads", "commission_paid")
    op.drop_column("product_downloads", "total_paid")
    # op.create_unique_constraint('unique_request_comment_vote', 'request_comment_votes', ['user_id', 'comment_id'])
    op.drop_constraint("unique_snagged_request", "snagged_requests", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_snagged_request", "snagged_requests", ["request_id", "developer_id"]
    )
    op.drop_constraint(
        "unique_request_comment_vote", "request_comment_votes", type_="unique"
    )
    op.add_column(
        "product_downloads",
        sa.Column(
            "total_paid",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "product_downloads",
        sa.Column(
            "commission_paid",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_unique_constraint(
        "product_downloads_transaction_id_key", "product_downloads", ["transaction_id"]
    )
    # ### end Alembic commands ###
