"""Playlits Relationship User Model

Revision ID: bcf69c18d4f2
Revises: b255d2c1a7b2
Create Date: 2025-04-14 10:52:32.428780

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bcf69c18d4f2"
down_revision: Union[str, None] = "b255d2c1a7b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
    pass
