"""Enhancing Note Taking Functionality

Revision ID: c098bae8c0ba
Revises: f32ea103237b
Create Date: 2024-10-31 04:34:35.819692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c098bae8c0ba'
down_revision: Union[str, None] = 'f32ea103237b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('unique_vote', 'votes', ['user_id', 'post_id'])
    # ### end Alembic commands ###
     pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_vote', 'votes', type_='unique')
    # ### end Alembic commands ###
