"""add stripe customer id

Revision ID: c0b717194469
Revises: 75917077b2fc
Create Date: 2024-12-05 14:03:29.994851

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c0b717194469"
down_revision: Union[str, None] = "75917077b2fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('unique_request_comment_vote', 'request_comment_votes', ['user_id', 'comment_id'])
    op.add_column("users", sa.Column("stripe_customer_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "stripe_customer_id")
    op.drop_constraint("unique_request_comment_vote", "request_comment_votes", type_="unique")
    # ### end Alembic commands ###
