"""add conversation content links

Revision ID: c1245660bc07
Revises: f295fe3e438e
Create Date: 2024-12-15 05:40:26.074024

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1245660bc07"
down_revision: Union[str, None] = "f295fe3e438e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_content_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["message_id"], ["conversation_messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id", "content_type", "content_id", name="unique_content_link"),
    )
    op.create_index(
        op.f("ix_conversation_content_links_id"), "conversation_content_links", ["id"], unique=False
    )
    # op.create_unique_constraint('unique_request_comment_vote', 'request_comment_votes', ['user_id', 'comment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_request_comment_vote", "request_comment_votes", type_="unique")
    op.drop_index(op.f("ix_conversation_content_links_id"), table_name="conversation_content_links")
    op.drop_table("conversation_content_links")
    # ### end Alembic commands ###
