"""add share_token to video_playlists

Revision ID: c755f2fdccc8
Revises: bcf69c18d4f2
Create Date: 2025-04-15 13:48:29.355466

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c755f2fdccc8"
down_revision: Union[str, None] = "bcf69c18d4f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "video_playlists", sa.Column("share_token", sa.String(), nullable=True)
    )
    op.create_unique_constraint(None, "video_playlists", ["share_token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "video_playlists", type_="unique")
    op.drop_column("video_playlists", "share_token")
    # ### end Alembic commands ###
