"""Initial migration

Revision ID: d357667f32c6
Revises: 
Create Date: 2024-10-10 04:29:12.142897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd357667f32c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_newsletter_email', table_name='newsletter')
    op.drop_index('ix_newsletter_id', table_name='newsletter')
    op.drop_table('newsletter')
    op.drop_index('ix_user_videos_id', table_name='user_videos')
    op.drop_table('user_videos')
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'email')
    op.create_unique_constraint('unique_vote', 'votes', ['user_id', 'post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_vote', 'votes', type_='unique')
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_column('users', 'username')
    op.create_table('user_videos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('video_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_videos_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_videos_pkey')
    )
    op.create_index('ix_user_videos_id', 'user_videos', ['id'], unique=False)
    op.create_table('newsletter',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='newsletter_pkey')
    )
    op.create_index('ix_newsletter_id', 'newsletter', ['id'], unique=False)
    op.create_index('ix_newsletter_email', 'newsletter', ['email'], unique=True)
    # ### end Alembic commands ###
