"""add_rating_fields_to_showcase

Revision ID: d79805351710
Revises: 0aea0cc44575
Create Date: 2025-01-06 15:06:38.999638

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d79805351710"
down_revision: Union[str, None] = "0aea0cc44575"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('unique_request_comment_vote', 'request_comment_votes', ['user_id', 'comment_id'])
    op.add_column("showcases", sa.Column("average_rating", sa.Float(), nullable=True))
    op.add_column("showcases", sa.Column("total_ratings", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("showcases", "total_ratings")
    op.drop_column("showcases", "average_rating")
    # op.drop_constraint('unique_request_comment_vote', 'request_comment_votes', type_='unique')
    # ### end Alembic commands ###
