"""Add video votes

Revision ID: d8b9781e389d
Revises: f44c1ad32d94
Create Date: 2024-12-12 19:36:02.224628

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8b9781e389d"
down_revision: Union[str, None] = "f44c1ad32d94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('unique_request_comment_vote', 'request_comment_votes', ['user_id', 'comment_id'])
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_request_comment_vote", "request_comment_votes", type_="unique")
    # ### end Alembic commands ###
