"""fixing backend model definition

Revision ID: dd31281a30d4
Revises: d21fa5f2a93b
Create Date: 2025-01-05 18:52:03.366473

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd31281a30d4"
down_revision: Union[str, None] = "d21fa5f2a93b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "showcases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("readme", sa.Text(), nullable=True),
        sa.Column("developer_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("video_ids", sa.ARRAY(sa.Integer()), nullable=True),
        sa.ForeignKeyConstraint(
            ["developer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_showcases_id"), "showcases", ["id"], unique=False)
    op.create_table(
        "showcase_ratings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("showcase_id", sa.Integer(), nullable=False),
        sa.Column("rater_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rater_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["showcase_id"],
            ["showcases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_showcase_ratings_id"), "showcase_ratings", ["id"], unique=False
    )
    # op.create_unique_constraint(
    #     "unique_request_comment_vote",
    #     "request_comment_votes",
    #     ["user_id", "comment_id"],
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_request_comment_vote', 'request_comment_votes', type_='unique')
    op.drop_index(op.f("ix_showcase_ratings_id"), table_name="showcase_ratings")
    op.drop_table("showcase_ratings")
    op.drop_index(op.f("ix_showcases_id"), table_name="showcases")
    op.drop_table("showcases")
    # ### end Alembic commands ###
