"""Update command note array columns

Revision ID: ece0b17f483e
Revises: fd4c726a3d69
Create Date: 2024-11-06 03:32:36.499365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece0b17f483e'
down_revision: Union[str, None] = 'fd4c726a3d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('unique_vote', 'votes', ['user_id', 'post_id'])
    # ### end Alembic commands ###
     pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_vote', 'votes', type_='unique')
    # ### end Alembic commands ###
