"""Add terms_accepted to users

Revision ID: ef642a5c5948
Revises: d8b9781e389d
Create Date: 2024-12-14 10:47:47.914748

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef642a5c5948"
down_revision: Union[str, None] = "d8b9781e389d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Add the column with a default value for existing rows
    op.add_column(
        "users",
        sa.Column("terms_accepted", sa.Boolean(), nullable=False, server_default="false"),
    )
    # Remove the default after adding the column to avoid setting it for future rows
    op.alter_column("users", "terms_accepted", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "terms_accepted")
    op.drop_constraint("unique_request_comment_vote", "request_comment_votes", type_="unique")
    # ### end Alembic commands ###
