"""Snagged Ticket Model

Revision ID: f77206e88025
Revises: 860850fe3d1d
Create Date: 2024-12-16 04:58:43.420921

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f77206e88025"
down_revision: Union[str, None] = "860850fe3d1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "snagged_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("developer_id", sa.Integer(), nullable=False),
        sa.Column(
            "snagged_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["developer_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["request_id"], ["requests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id", "developer_id", name="unique_snagged_request"),
    )
    op.create_index(op.f("ix_snagged_requests_id"), "snagged_requests", ["id"], unique=False)
    # op.create_unique_constraint('unique_request_comment_vote', 'request_comment_votes', ['user_id', 'comment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_request_comment_vote", "request_comment_votes", type_="unique")
    op.drop_index(op.f("ix_snagged_requests_id"), table_name="snagged_requests")
    op.drop_table("snagged_requests")
    # ### end Alembic commands ###
